-- SUPABASE SCHEMA DEFINITION: WOW SALON ADMIN
-- Execute this entire script in the Supabase SQL Editor.

--------------------------------------------------------
-- 1. DROP EXISTING TABLES
--------------------------------------------------------
DROP TABLE IF EXISTS public.staff_commissions CASCADE;
DROP TABLE IF EXISTS public.visit_products CASCADE;
DROP TABLE IF EXISTS public.visit_services CASCADE;
DROP TABLE IF EXISTS public.customer_visits CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.staff CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;

--------------------------------------------------------
-- 2. CREATE CORE ENTITY TABLES
--------------------------------------------------------

-- Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    dob DATE,
    services_taken TEXT[], -- Array of service names
    staff_served TEXT[],   -- Array of staff names
    amount_paid NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;

-- Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    price NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.services DISABLE ROW LEVEL SECURITY;

-- Staff Table
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    gender TEXT,
    salary NUMERIC DEFAULT 0,
    service_revenue NUMERIC DEFAULT 0,
    commission_earned NUMERIC DEFAULT 0, -- 10% Commission
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.staff DISABLE ROW LEVEL SECURITY;

-- Products (Inventory) Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    purchased_quantity INTEGER NOT NULL DEFAULT 0,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    salon_consumption INTEGER NOT NULL DEFAULT 0,
    current_stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;

-- Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Electricity', 'Water', 'Rent', 'Internet', 'Other Expenses')),
    amount NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;

--------------------------------------------------------
-- 3. CREATE TRANSACTION & MAPPING TABLES
--------------------------------------------------------

-- Customer Visits (Master Transaction Record)
CREATE TABLE IF NOT EXISTS public.customer_visits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    visit_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    service_total NUMERIC DEFAULT 0,
    product_total NUMERIC DEFAULT 0,
    grand_total NUMERIC DEFAULT 0,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.customer_visits DISABLE ROW LEVEL SECURITY;

-- Visit Services Mapping
CREATE TABLE IF NOT EXISTS public.visit_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_services DISABLE ROW LEVEL SECURITY;

-- Visit Products Mapping
CREATE TABLE IF NOT EXISTS public.visit_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_products DISABLE ROW LEVEL SECURITY;

-- Staff Commissions Table
CREATE TABLE IF NOT EXISTS public.staff_commissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_amount NUMERIC NOT NULL DEFAULT 0,
    commission_amount NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.staff_commissions DISABLE ROW LEVEL SECURITY;

--------------------------------------------------------
-- 4. CREATE INDEXES FOR PERFORMANCE
--------------------------------------------------------

-- Indexes for Customers
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers(name);

-- Indexes for Customer Visits
CREATE INDEX IF NOT EXISTS idx_visits_date ON public.customer_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_visits_customer_id ON public.customer_visits(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_staff_id ON public.customer_visits(staff_id);

-- Indexes for Visit Services
CREATE INDEX IF NOT EXISTS idx_visit_services_visit_id ON public.visit_services(visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_services_service_id ON public.visit_services(service_id);

-- Indexes for Visit Products
CREATE INDEX IF NOT EXISTS idx_visit_products_visit_id ON public.visit_products(visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_products_product_id ON public.visit_products(product_id);

-- Indexes for Staff Commissions
CREATE INDEX IF NOT EXISTS idx_commissions_staff_id ON public.staff_commissions(staff_id);
CREATE INDEX IF NOT EXISTS idx_commissions_created_at ON public.staff_commissions(created_at);

-- Indexes for Expenses
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(date);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON public.expenses(category);

-- Indexes for Products
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);

--------------------------------------------------------
-- 5. SEED DEFAULT DATA
--------------------------------------------------------

INSERT INTO public.services (service_name, category, price) VALUES 
-- 1. Hair Services
('Hair Cuts', 'Hair Services', 0),
('Shampoo & Conditioning', 'Hair Services', 0),
('Deep Conditioning', 'Hair Services', 0),
('Head Massage', 'Hair Services', 0),
('Hair Styling', 'Hair Services', 0),
('Hair Spa (L''Oréal)', 'Hair Services', 0),
-- 2. Hair Treatments
('Hair Fall Treatment', 'Hair Treatments', 0),
('Anti-Dandruff Treatment', 'Hair Treatments', 0),
('Keratin Treatment', 'Hair Treatments', 0),
-- 3. Hair Colour Services
('L''Oréal Global Colour', 'Hair Colour Services', 0),
('Godrej Root Touch-Up', 'Hair Colour Services', 0),
('L''Oréal Highlighting', 'Hair Colour Services', 0),
('Ombre Colour', 'Hair Colour Services', 0),
('Balayage Colour', 'Hair Colour Services', 0),
-- 4. Hair Smoothing Services
('Smoothing (L''Oréal Xtenso)', 'Hair Smoothing Services', 0),
('Botox Treatment', 'Hair Smoothing Services', 0),
('Keratin Smoothing', 'Hair Smoothing Services', 0),
('Kera Smooth', 'Hair Smoothing Services', 0),
('Botox Smooth', 'Hair Smoothing Services', 0),
-- 5. Beauty Services
('Threading', 'Beauty Services', 0),
('Waxing', 'Beauty Services', 0),
('Bleach & D-Tan', 'Beauty Services', 0),
('Services Only for Women', 'Beauty Services', 0),
('Bridal Services', 'Beauty Services', 0),
('Bridal Makeup', 'Beauty Services', 0),
('4 Types of Bridal Packages', 'Beauty Services', 0),
('Clean-Up', 'Beauty Services', 0),
('Facial', 'Beauty Services', 0),
('Special Mask Treatment', 'Beauty Services', 0),
('Lotus Eye Treatment', 'Beauty Services', 0),
('Face Treatment', 'Beauty Services', 0),
('Manicure', 'Beauty Services', 0),
('Pedicure', 'Beauty Services', 0),
('Nail Polish', 'Beauty Services', 0),
('Skin Polishing', 'Beauty Services', 0),
('Services Only for Men', 'Beauty Services', 0),
('Groom Services', 'Beauty Services', 0),
('HD Makeup', 'Beauty Services', 0),
('3 Types of Groom packages', 'Beauty Services', 0);
