-- SUPABASE SCHEMA DEFINITION

-- 1. Create Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    duration INTEGER NOT NULL DEFAULT 30,
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Staff Table
CREATE TABLE IF NOT EXISTS public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name TEXT,
    name TEXT,
    gender TEXT,
    phone TEXT,
    joining_date DATE,
    salary NUMERIC DEFAULT 15000,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Customer Visits Base Table
CREATE TABLE IF NOT EXISTS public.customer_visits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    visit_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    service_total NUMERIC DEFAULT 0,
    product_total NUMERIC DEFAULT 0,
    grand_total NUMERIC DEFAULT 0,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Visit Services Mapping Table
CREATE TABLE IF NOT EXISTS public.visit_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0
);

-- 5. Visit Products Mapping Table
CREATE TABLE IF NOT EXISTS public.visit_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    product_id TEXT,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL DEFAULT 0
);

-- 6. Staff Commissions Table
CREATE TABLE IF NOT EXISTS public.staff_commissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_amount NUMERIC NOT NULL DEFAULT 0,
    commission_amount NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
